### ISSUE TITLE
Support for puppet-syntax 3.x needed

### ISSUE THREAD

**Issue by genebean** [declarativesystems/onceover-codequality#17]
It seems that this gem does not yet support the latest puppet-syntax gem.

**Comment by GeoffWilliams** [comment]
You are correct. 

Is anyone interested in taking over maintenance of this gem? I'm not working on Puppet at the moment

**Comment by GeoffWilliams** [comment]
fix released in 0.8.0, thanks @kreeuwijk for the fix
