### ISSUE TITLE
puppet-lint renamed to puppetlabs-puppet-lint

### ISSUE THREAD

**Issue by ChrLau** [declarativesystems/onceover-codequality#30]
Hi, with https://github.com/puppetlabs/puppet-lint/pull/158 the puppet-lint Gem has been renamed to puppetlabs-puppet-lint. And now we are getting all sorts of warnings in our CI-Pipeline when we run the linting check with `onceover run codequality --no_docs --no_puppetfile --no_syntax`.

The warnings are the same as those mentioned in https://github.com/puppetlabs/puppet-lint/issues/169.
There it's stated that this is happening when puppet-lint and puppetlabs-puppet-lint are used at the same time.

Are you able to update your dependencies to puppetlabs-puppet-lint?

Thanks!

**Comment by GeoffWilliams** [comment]
fix released in 0.11.0

**Comment by ChrLau** [comment]
Thanks  @GeoffWilliams !

**Comment by alexjfisher** [comment]
and now I have both `puppet-lint`, (because almost all lint plugins depend on the original gem!), and `puppetlabs-puppet-lint` installed into my builds, and this is not good...

**Comment by alexjfisher** [comment]
Also keep an eye out for the name of the binary changing... https://github.com/puppetlabs/puppet-lint/pull/170/files#diff-f285faa44ba3d78ef73a0305522f63837a0e68799489cfb2bb66b72a431db86c
