### ISSUE TITLE
Tag 0.12.0 missing in the GitHub repo

### ISSUE THREAD

**Issue by smortex** [declarativesystems/onceover-codequality#34]
Hey

[The latest version of the gem on rubygems.org](https://rubygems.org/gems/onceover-codequality) is 0.12.0, but [the latest tag on the repo](https://github.com/declarativesystems/onceover-codequality/tags) is 0.11.0.

Can you please make sure the tag is pushed to GitHub?

Thanks!

**Comment by GeoffWilliams** [comment]
good catch! done
