### ISSUE TITLE
The .puppet-lint.rc file is ignored

### ISSUE THREAD

**Issue by franknarf8** [declarativesystems/onceover-codequality#8]
Hello,

The `.puppet-lint.rc` file seems to be ignored; I think the culprit might be the following line : https://github.com/declarativesystems/onceover-codequality/blob/master/lib/onceover/codequality/lint.rb#L28

Since we are changing directory, `puppet-lint` doesn't find the `.puppet-lint.rc` in the same directory, as it is a few directories above. `puppet-lint` looks for `.puppet-lint.rc` in the current working directory, or in two other global directories ([See Configuration files locations.](https://github.com/rodjek/puppet-lint#configuration-file))

A solution to solve this would be to give the path `p` to the `path` argument of `puppet-lint`, instead of changing folders.

A really dumb and inconvenient workaround would be copying the `.puppet-lint.rc` in every linted paths.

Thanks again for looking into this :)

- Frank

**Comment by GeoffWilliams** [comment]
Fixed in master- thanks very much!
